In [1]:
import pandas as pd
df=pd.read_parquet("./data/process/dataset_final_graphrag.parquet")
df.head()

,system,user,assistant,entities_json,relationships_json
0,Bạn là một trợ lý AI am hiểu về lịch sử Việt N...,Nguyễn Huệ (Quang Trung) đã làm gì để dẫn đến ...,Bối cảnh: Ngọc Hồi – Đống Đa (Quang Trung) thu...,"{""Nguoi"": [""Nguyễn Huệ"", ""Quang Trung""], ""DiaD...","{""new_nodes"": {""SuKien"": [""Ngọc Hồi – Đống Đa ..."
1,Bạn là chuyên gia sử học Việt Nam. Có thể nêu ...,Kể về Gia Long (Nguyễn Ánh) và đóng góp của ôn...,Câu hỏi nhắm tới sự kiện Nguyễn Ánh lên ngôi G...,"{""Nguoi"": [""Long"", ""Gia Long"", ""Nguyễn Ánh""], ...","{""new_nodes"": {""SuKien"": [""Nguyễn Ánh lên ngôi..."
2,Bạn là một trợ lý AI am hiểu về lịch sử Việt N...,Năm 1527 ở Việt Nam diễn ra sự kiện gì quan tr...,Bối cảnh: Mạc Đăng Dung lập nhà Mạc thuộc Nhà ...,"{""Nguoi"": [""Lê trung hưng"", ""Lê trung"", ""Mạc Đ...","{""new_nodes"": {""SuKien"": [""Lập nhà Mạc""], ""Van..."
3,Bạn là chuyên gia sử học Việt Nam. Có thể nêu ...,Trình bày nhanh những điểm chính về Ký kết CPTPP.,Để trả lời: Ký kết CPTPP diễn ra năm 2018. Nội...,"{""MocThoiGian"": [""Năm 2018""], ""MISCELLANEOUS"":...","{""new_nodes"": {""SuKien"": [""Ký kết CPTPP""], ""Va..."
4,Bạn là chuyên gia sử học Việt Nam. Có thể nêu ...,Hậu quả hay tác động dài hạn của Đại Việt đánh...,Để trả lời: Đại Việt đánh bại Champa tại Vijay...,"{""DiaDanh"": [""Đại Việt"", ""kinh đô Vijaya"", ""ph...","{""new_nodes"": {""SuKien"": [""Đại Việt đánh bại C..."

In [2]:
df

,system,user,assistant,entities_json,relationships_json
0,Bạn là một trợ lý AI am hiểu về lịch sử Việt N...,Nguyễn Huệ (Quang Trung) đã làm gì để dẫn đến ...,Bối cảnh: Ngọc Hồi – Đống Đa (Quang Trung) thu...,"{""Nguoi"": [""Nguyễn Huệ"", ""Quang Trung""], ""DiaD...","{""new_nodes"": {""SuKien"": [""Ngọc Hồi – Đống Đa ..."
1,Bạn là chuyên gia sử học Việt Nam. Có thể nêu ...,Kể về Gia Long (Nguyễn Ánh) và đóng góp của ôn...,Câu hỏi nhắm tới sự kiện Nguyễn Ánh lên ngôi G...,"{""Nguoi"": [""Long"", ""Gia Long"", ""Nguyễn Ánh""], ...","{""new_nodes"": {""SuKien"": [""Nguyễn Ánh lên ngôi..."
2,Bạn là một trợ lý AI am hiểu về lịch sử Việt N...,Năm 1527 ở Việt Nam diễn ra sự kiện gì quan tr...,Bối cảnh: Mạc Đăng Dung lập nhà Mạc thuộc Nhà ...,"{""Nguoi"": [""Lê trung hưng"", ""Lê trung"", ""Mạc Đ...","{""new_nodes"": {""SuKien"": [""Lập nhà Mạc""], ""Van..."
3,Bạn là chuyên gia sử học Việt Nam. Có thể nêu ...,Trình bày nhanh những điểm chính về Ký kết CPTPP.,Để trả lời: Ký kết CPTPP diễn ra năm 2018. Nội...,"{""MocThoiGian"": [""Năm 2018""], ""MISCELLANEOUS"":...","{""new_nodes"": {""SuKien"": [""Ký kết CPTPP""], ""Va..."
4,Bạn là chuyên gia sử học Việt Nam. Có thể nêu ...,Hậu quả hay tác động dài hạn của Đại Việt đánh...,Để trả lời: Đại Việt đánh bại Champa tại Vijay...,"{""DiaDanh"": [""Đại Việt"", ""kinh đô Vijaya"", ""ph...","{""new_nodes"": {""SuKien"": [""Đại Việt đánh bại C..."
...,...,...,...,...,...
21938,Bạn là chuyên gia sử học Việt Nam. Có thể nêu ...,Vì sao Chiến dịch Hồ Chí Minh – Giải phóng miề...,B1: gắn mốc 1975 với Chiến dịch Hồ Chí Minh – ...,"{""DiaDanh"": [""Việt Nam"", ""Sài Gòn"", ""miền Nam""...","{""new_nodes"": {""SuKien"": [""Chiến dịch Hồ Chí M..."
21939,Bạn là trợ lý lịch sử Việt Nam. Hãy giải thích...,"Trong năm 1054, điều gì có ý nghĩa lịch sử ở V...",Để trả lời: Đổi quốc hiệu thành Đại Việt diễn ...,"{""DiaDanh"": [""Việt Nam"", ""Đại Việt"", ""Thánh Tô...","{""new_nodes"": {""SuKien"": [""Đổi quốc hiệu thành..."
21940,Bạn là chuyên gia sử học Việt Nam. Có thể nêu ...,Hãy cho biết sự kiện tiêu biểu của Việt Nam và...,Câu hỏi nhắm tới sự kiện Đổi quốc hiệu thành Đ...,"{""DiaDanh"": [""Việt Nam"", ""Đại Việt"", ""Thánh Tô...","{""new_nodes"": {""SuKien"": [""Đổi quốc hiệu thành..."
21941,Bạn là một trợ lý AI am hiểu về lịch sử Việt N...,"Trong năm 1905, điều gì có ý nghĩa lịch sử ở V...",1905: Phong trào Đông Du. Phan Bội Châu khởi x...,"{""Nguoi"": [""Phan Bội Châu""], ""DiaDanh"": [""Việt...","{""new_nodes"": {""SuKien"": [""Phong trào Đông Du""..."
21942,Bạn là một trợ lý AI am hiểu về lịch sử Việt N...,Hãy cho biết sự kiện tiêu biểu của Việt Nam và...,B1: gắn mốc 1054 với Đổi quốc hiệu thành Đại V...,"{""DiaDanh"": [""Việt Nam"", ""Đại Việt"", ""Thánh Tô...","{""new_nodes"": {""SuKien"": ["" Đổi quốc hiệu thàn..."